version: '3'
services:
  postgres:
    image: postgres:14.1-alpine
    env_file:
      - ./postgres/.env
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./backend/src/infra/postgres/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
  api:
    build:
      context: ./backend
    restart: always
    depends_on:
      - postgres
    ports:
      - '5000:5000'
volumes:
  db: